#!/usr/bin/env python

import sys, json

from urllib import quote

try:
    import urllib2 as request
except ImportError:
    from urllib import request


class Sems():

    def __init__(self, url):
        self.url = url

    def print_monitor_statuses(self):
        monitors = self.__get_monitors()
        self.__print_monitors(monitors)

    def __get_monitors(self):
        api = "%s/api/monitors" % self.url
        response = request.urlopen(api).read()
        return json.loads(response)['data']['monitors']

    def __print_monitors(self, monitors):
        for monitor in monitors:
            is_active = self.__is_active(monitor)
            if is_active:
                color = "#00ff00"
            else:
                color = "#ff0000"
            print("${color %s}%s$color" % (color, monitor['label']))

    def __is_active(self, monitor):
        api = "%s/api/monitors/%s/check" % (self.url, quote(monitor['label']))
        response = request.urlopen(api).read()
        return json.loads(response)['data']['alive']

if __name__ == "__main__":

    print "SEMS %s" % sys.argv[1]
    sems = Sems(sys.argv[1])
    sems.print_monitor_statuses()

